name: Gen Internal Docs

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'

jobs:
  dev-docs-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Update to DevDocs
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          API_KEY=${{ secrets.API_KEY }}
          REPO_GH_PAT=${{secrets.REPO_GH_PAT}}
          GITHUB_REPOSITORY="${{ github.repository }}"
          GITHUB_ACTOR="${{ github.actor }}"
          # curl -X POST -H "Content-Type: application/json" \
          #      -H "X-API-KEY: $API_KEY" \
          #      -d '{"apiKey": "'$API_KEY'", "repo_gh_pat": "'$REPO_GH_PAT'", "githubRepository": "'$GITHUB_REPOSITORY'", "default_time": 50}' \
          #      "${{ secrets.GENERATE_ENDPOINT_URL }}"
          curl --location 'https://hx3cymrjm2.us-east-1.awsapprunner.com/company/spriteai/generate_internal_docs' \
            --header 'Content-Type: application/json' \
            --data '{
                "githubRepository": "team-dev-docs/spriteAI",
                "apiKey": "'$API_KEY'",
                "default_time": 50,
                "repo_gh_pat": "'$REPO_GH_PAT'"
            }'
        env:
          API_KEY: ${{ secrets.API_KEY }}
