name: Semantic Analysis for JavaScript

on: [push]

jobs:
  setup-semantic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 # Ensures the current and previous commits are checked out

    - name: Install GHC and Cabal with ghcup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
        echo "source $HOME/.ghcup/env" >> $GITHUB_ENV
        ghcup install ghc 8.10.1
        ghcup set ghc 8.10.1
        ghcup install cabal
        cabal update

    - name: Clone semantic
      run: |
        git clone https://github.com/github/semantic.git
        cd semantic
        script/bootstrap
        cabal v2-build all

    - name: Find Modified JavaScript Files
      id: files
      run: |
        echo "CHANGED_JS_FILES<<EOF" >> $GITHUB_ENV
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js$' >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Print Modified JavaScript Files
      run: |
        echo "Modified JavaScript Files:"
        echo "$CHANGED_JS_FILES"

    - name: Run semantic analysis on Modified JavaScript Files
      if: env.CHANGED_JS_FILES != ''
      run: |
        cd semantic
        for file in $CHANGED_JS_FILES; do
          echo "Generating symbols for $file"
          cabal v2-run semantic:semantic -- parse --json-symbols $file
        done
