name: Find Modified JavaScript Functions

on: [push, pull_request]

jobs:
  find-functions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Tree-sitter CLI and JavaScript grammar
      run: |
        npm install -g tree-sitter-cli tree-sitter-javascript

    - name: Find modified JavaScript files
      id: modified-files
      run: |
        echo "Modified files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.js'

    - name: Parse and find functions in modified files
      run: |
        for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.js'); do
          echo "Parsing $file"
          tree-sitter parse "$file" --query='(function_declaration name: (identifier) @function)' --output functions.json
          cat functions.json
        done
