name: Find JavaScript Functions

on: [push, pull_request]

jobs:
  find-functions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Tree-sitter CLI and JavaScript grammar
      run: |
        npm install -g tree-sitter-cli tree-sitter-javascript

    - name: Find all JavaScript files
      id: find-files
      run: |
        files=$(find . -name "*.js" -not -path "./node_modules/*")
        echo "::set-output name=js_files::$files"

    - name: Parse and find functions in all JavaScript files
      run: |
        for file in ${{ steps.find-files.outputs.js_files }}; do
          echo "Parsing $file"
          tree-sitter parse "$file" --query='(function_declaration name: (identifier) @function)' --output functions.json
          cat functions.json
        done
