name: Check and Generate Internal Docs from Issue

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
  issues:
    types: [opened, edited]
    title:
      startsWith: 'dev-docs-issue:'

jobs:
  dev-docs-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Update to DevDocs
        run: |
          API_KEY=${{ secrets.API_KEY }}
          REPO_GH_PAT=${{secrets.REPO_GH_PAT}}
          GITHUB_REPOSITORY="${{ github.repository }}"
          GITHUB_ACTOR="${{ github.actor }}"
          curl -X POST -H "Content-Type: application/json" \
               -H "X-API-KEY: $API_KEY" \
               -d '{"apiKey": "'$API_KEY'", "repo_gh_pat": "'$REPO_GH_PAT'", "default_time": 10, "githubRepository": "'$GITHUB_REPOSITORY'", "githubActor": "'$GITHUB_ACTOR'"}' \
               "${{ secrets.GENERATE_ENDPOINT_URL }}"
        env:
          API_KEY: ${{ secrets.API_KEY }}
